version: '3'

services:
  telegraf:
    image: telegraf:1.4.0
    volumes:
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:Z
      - /var/run/docker.sock:/var/run/docker.sock:Z
    privileged: true
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
  influxdb:
    image: influxdb:1.3.5
    volumes:
      - influxdbv:/var/lib/influxdb:Z
      # FAGZAL:
      - ./etc/influxdb.conf:/etc/influxdb/influxdb.conf:Z
    ports:
      - "8086:8086"
  chronograf:
    image: chronograf:latest
    environment:
      INFLUXDB_URL: http://influxdb:8086
      BASE_PATH: /chronograf
    ports:
      - "8888:8888"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafanav:/var/lib/grafana:Z
    ports:
      - "3000:3000"
    env_file:
      - './env.grafana'

volumes:
        influxdbv:
        grafanav:
